export interface DefaultCategoryMatchRule {
  id: string;
  pattern: string;
  categoryName: string;
  priority: number;
  note?: string;
}

export const deprecatedDefaultCategoryMatchRuleIds = [
  "catrule-currency-conversion-fee",
  "catrule-goldenvillageigv",
  "catrule-evergreen-stationery",
  "catrule-korean-air-spaced",
  "catrule-tway-airlines",
  "catrule-starhub"
];

export const defaultCategoryMatchRules: DefaultCategoryMatchRule[] = [
  { id: "catrule-paynow-wise-asia-pacific", pattern: "PAYNOW-FAST WISE ASIA-PACIFIC", categoryName: "Family & Personal", priority: 5 },
  { id: "catrule-card-transfer-tsfto", pattern: "TSFTO", categoryName: "Transfer", priority: 8, note: "Card activity shorthand for transfer to an account/card ending in the trailing digits." },
  { id: "catrule-moneysend", pattern: "MONEYSEND", categoryName: "Transfer", priority: 8 },
  { id: "catrule-new-creation-church", pattern: "NEW CREATION CHURCH", categoryName: "Church", priority: 10 },
  { id: "catrule-joseph-prince", pattern: "JOSEPHPRINCE", categoryName: "Subscriptions MO", priority: 15 },
  { id: "catrule-conversion-fee", pattern: "CONVERSIONFEE", categoryName: "Fees", priority: 15 },
  { id: "catrule-income-insurance", pattern: "INCOMEINSURANCE", categoryName: "Insurance", priority: 20 },
  { id: "catrule-singlife", pattern: "SINGLIFE", categoryName: "Insurance", priority: 20 },
  { id: "catrule-keppel-electric", pattern: "KEPPEL ELECTRIC", categoryName: "Bills", priority: 25 },
  { id: "catrule-axs", pattern: "AXSPTELTD", categoryName: "Bills", priority: 25 },
  { id: "catrule-starhub-bills", pattern: "STARHUB", categoryName: "Bills", priority: 25 },
  { id: "catrule-m1-limited", pattern: "M1LIMITED", categoryName: "Bills", priority: 25 },
  { id: "catrule-m1-ltd", pattern: "M1LTD", categoryName: "Bills", priority: 25, note: "Compact Citi card text for M1 recurring mobile bill." },
  { id: "catrule-m1-app", pattern: "M1APP", categoryName: "Bills", priority: 25 },
  { id: "catrule-apple-bill", pattern: "APPLE.COM/BILL", categoryName: "Subscriptions MO", priority: 30 },
  { id: "catrule-youtube-premium", pattern: "YOUTUBEPREMIUM", categoryName: "Subscriptions MO", priority: 30 },
  { id: "catrule-google-youtube", pattern: "GOOGLE*YOUTUBE", categoryName: "Subscriptions MO", priority: 30 },
  { id: "catrule-openai", pattern: "OPENAI", categoryName: "Subscriptions MO", priority: 30 },
  { id: "catrule-anywhere", pattern: "ANYWHERE", categoryName: "Subscriptions MO", priority: 30 },
  { id: "catrule-hello-ride", pattern: "HELLO RIDE", categoryName: "Subscriptions MO", priority: 30 },
  { id: "catrule-anywheel", pattern: "ANYWHEEL", categoryName: "Subscriptions MO", priority: 30 },
  { id: "catrule-vivifi", pattern: "VIVIFI", categoryName: "Bills", priority: 25, note: "Mobile bill." },
  { id: "catrule-tada", pattern: "TADA", categoryName: "Taxi", priority: 35 },
  { id: "catrule-gopay-gojek", pattern: "GOPAY-GOJEK", categoryName: "Taxi", priority: 35 },
  { id: "catrule-grab", pattern: "GRAB", categoryName: "Taxi", priority: 35 },
  { id: "catrule-tennis", pattern: "TENNIS", categoryName: "Sports & Hobbies", priority: 35 },
  { id: "catrule-myactive-sg", pattern: "MYACTIVESG", categoryName: "Sports & Hobbies", priority: 35 },
  { id: "catrule-bus-mrt", pattern: "BUS/MRT", categoryName: "Public Transport", priority: 40 },
  { id: "catrule-fairprice", pattern: "FAIRPRICE", categoryName: "Groceries", priority: 45 },
  { id: "catrule-don-don-donki", pattern: "DON DON DONKI", categoryName: "Groceries", priority: 45 },
  { id: "catrule-cs-fresh", pattern: "CS FRESH", categoryName: "Groceries", priority: 45 },
  { id: "catrule-little-farms", pattern: "LITTLE FARMS", categoryName: "Groceries", priority: 45 },
  { id: "catrule-meidi-ya", pattern: "MEIDI-YA", categoryName: "Groceries", priority: 45 },
  { id: "catrule-foodloft", pattern: "FOODLOFT", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-nets-debit-consumer", pattern: "NETS Debit-Consumer", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-vending", pattern: "VENDING", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-bm-nasi", pattern: "BMV NASI", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-vietnamese-food", pattern: "VIETNAMESE", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-alhamdulillah-food", pattern: "ALHAMDULILL", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-shake-shack", pattern: "SHAKE SHACK", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-sabai-sabai", pattern: "SABAI SABAI", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-paris-baguette", pattern: "PARIS BAGUETTE", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-pepper-kitchen", pattern: "PEPPER KITCHEN", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-mcdonalds", pattern: "MCDONALDS", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-daily-cut", pattern: "THE DAILY CUT", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-fu-ji-yong-tau-foo", pattern: "FU JI YONG TAU FOO", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-seven-eleven", pattern: "7-ELEVEN", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-ichiban-boshi", pattern: "ICHIBAN BOSHI", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-tori-q", pattern: "TORI-Q", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-krispy-kreme", pattern: "KRISPY KREME", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-sanpoutei-ramen", pattern: "SANPOUTEI RAMEN", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-gochisoshokudo", pattern: "GOCHISOSHOKUDO", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-starbucks", pattern: "STARBUCKS", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-llao-llao", pattern: "LLAO LLAO", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-toast-box", pattern: "TOAST BOX", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-genki-sushi", pattern: "GENKI SUSHI", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-old-chang-kee", pattern: "OLD CHANG KEE", categoryName: "Food & Drinks", priority: 45 },
  { id: "catrule-fr-wisma", pattern: "FR WISMA", categoryName: "Food & Drinks", priority: 45, note: "Food Republic Wisma foodcourt." },
  { id: "catrule-creative-salon", pattern: "CREATIVE SALON", categoryName: "Beauty", priority: 45 },
  { id: "catrule-natureland", pattern: "NATURELAND", categoryName: "Beauty", priority: 45 },
  { id: "catrule-aircon-uncle", pattern: "AIRCON UNCLE", categoryName: "Home", priority: 45 },
  { id: "catrule-coin-laundry", pattern: "COIN LAUNDRY", categoryName: "Travel", priority: 45 },
  { id: "catrule-interests", pattern: "INTERESTS", categoryName: "Fees", priority: 45 },
  { id: "catrule-late-charges", pattern: "LATE CHARGES", categoryName: "Fees", priority: 45 },
  { id: "catrule-golden-village", pattern: "GOLDENVILLAGE", categoryName: "Entertainment", priority: 50 },
  { id: "catrule-gv", pattern: "GV", categoryName: "Entertainment", priority: 55, note: "Short merchant token; keep lower priority than exact cinema names." },
  { id: "catrule-shaw-theatres", pattern: "SHAW THEATRES", categoryName: "Entertainment", priority: 50 },
  { id: "catrule-shopee", pattern: "SHOPEE", categoryName: "Shopping", priority: 60 },
  { id: "catrule-amazon", pattern: "AMAZON", categoryName: "Shopping", priority: 60 },
  { id: "catrule-amzon", pattern: "AMZON", categoryName: "Shopping", priority: 60 },
  { id: "catrule-stationery", pattern: "STATIONERY", categoryName: "Shopping", priority: 60 },
  { id: "catrule-ikea", pattern: "IKEA", categoryName: "Shopping", priority: 60 },
  { id: "catrule-muji", pattern: "MUJI", categoryName: "Shopping", priority: 60 },
  { id: "catrule-takashimaya", pattern: "TAKASHIMAYA", categoryName: "Shopping", priority: 60 },
  { id: "catrule-uniqlo", pattern: "UNIQLO", categoryName: "Shopping", priority: 60 },
  { id: "catrule-jal-airline", pattern: "JALAIRLINE", categoryName: "Travel", priority: 65 },
  { id: "catrule-japan-airlines", pattern: "JAPAN AIRLINES", categoryName: "Travel", priority: 65 },
  { id: "catrule-korean-air", pattern: "KOREANAIR", categoryName: "Travel", priority: 65 },
  { id: "catrule-tway-air", pattern: "TWAYAIR", categoryName: "Travel", priority: 65 }
];
