export const messages = {
  common: {
    loading: "Loading...",
    bootstrapErrorTitle: "Dashboard data could not load.",
    emptyValue: "—",
    viewingDot: (label) => `Viewing • ${label}`,
    contextWithView: (left, right) => `${left} • ${right}`,
    triplet: (first, second, third) => `${first} • ${second} • ${third}`,
    moneyAndPercent: (moneyValue, percentage) => `${moneyValue} • ${percentage}%`
  },
  views: {
    household: "Household"
  },
  tabs: {
    summary: "Summary",
    month: "Month",
    entries: "Entries",
    splits: "Splits",
    imports: "Imports",
    settings: "Settings",
    faq: "FAQ",
    ariaLabel: "Dashboard sections"
  },
  period: {
    month: "Month",
    year: "Range",
    currentYear: "2025",
    previousAriaLabel: "Previous period",
    nextAriaLabel: "Next period"
  },
  summary: {
    spendingMix: "Spending Mix",
    rangeOverall: "Range overall",
    fromMonth: "From",
    toMonth: "To",
    focusMonth: "Focus",
    intentVsOutcome: "Intent vs Outcome",
    intentVsOutcomeDetail: "Monthly comparison with expandable detail.",
    incomeLabel: (value) => `${value} income`,
    totalSpend: "Total spend",
    table: {
      metric: "Metric",
      estimate: "Planned",
      actual: "Actual",
      variance: "Variance",
      note: "Context",
      expectedExpenses: "Expected spend",
      expectedSavings: "Savings goal",
      actualSavings: "Realized savings"
    }
  },
  month: {
    incomeSectionTitle: "Income",
    incomeSectionDetail: "Planned income sources that fund the month before expenses are allocated.",
    actions: "Actions",
    duplicateMonth: "Duplicate month",
    resetMonth: "Reset month",
    resetMonthDetail: "This clears the current month's plan rows, entries, and summary totals.",
    resetMonthPlaceholder: "Type 'reset month'",
    resetMonthConfirm: "Confirm reset month",
    deleteMonth: "Delete month",
    deleteMonthDetail: "This removes the current month entirely from the demo, including its summary snapshot.",
    deleteMonthPlaceholder: "Type 'delete month'",
    deleteMonthConfirm: "Confirm delete month",
    addIncomeSource: "+ Add income source",
    incomeRowNote: "Main planned income source for the month.",
    extraIncomeNote: "Additional planned income source.",
    addPlannedItem: "+ Add planned item",
    addBudgetBucket: "+ Add budget bucket",
    newPlannedItemNote: "New planned item.",
    newBudgetBucketNote: "New budget bucket.",
    doneEdit: "Done",
    cancelEdit: "Cancel",
    notesTitle: "Monthly Note",
    notesDetail: "Why the month looked like this.",
    accountsTitle: "Accounts",
    accountsDetail: "Tracked finance accounts.",
    editHint: "Click a row to edit the plan. Actual stays read-only because it should come from entries.",
    readOnlyCombinedHint: "Combined household view is read-only. Switch to a person view to edit the plan.",
    table: {
      category: "Category",
      day: "Date",
      item: "Item",
      planned: "Planned",
      actual: "Actual",
      variance: "Variance",
      total: "Total",
      account: "Account",
      note: "Note"
    }
  },
  entries: {
    viewing: (label) => `Viewing entries for ${label}`,
    wallet: "By wallet",
    category: "By category",
    person: "By people",
    resetFilters: "Reset filters",
    allWallets: "All wallets",
    allCategories: "All categories",
    allPeople: "All people",
    type: "By type",
    allTypes: "All types",
    totalsLabel: "Entry totals",
    totalSpend: "Spend",
    totalIncome: "Income",
    totalDifference: "Difference",
    dateNet: "Daily net",
    addEntry: "+ Add entry",
    editCategory: "Category",
    editDate: "Date",
    editType: "Type",
    editAmount: "Amount",
    editDescription: "Description",
    editWallet: "Wallet",
    editOwner: "Owner",
    editSplit: "Split %",
    editNote: "Note",
    editTransferDirection: "Transfer direction",
    scope: "Scope",
    shared: "Shared",
    offsetsCategory: " • offsets category",
    split: "Split",
    counterpart: "Counterpart",
    doneEdit: "Done",
    cancelEdit: "Cancel",
    addToSplits: "Add to splits"
  },
  splits: {
    viewing: (label) => `Viewing splits for ${label}`,
    nonGroup: "Non-group expenses",
    addGroup: "+",
    matches: "Matches",
    entries: "entries",
    allClear: "All clear",
    toReview: (count) => `${count} to review`,
    expenseMatches: "Expense matches",
    settlementMatches: "Settlement matches",
    addExpense: "+ Add expense",
    settleUp: "Settle up",
    settledUp: "Settled up",
    noGroups: "No split groups yet.",
    noEntries: "No split entries yet for this group.",
    noMatches: "No split matches to review right now.",
    youAreOwed: "You are owed",
    youOwe: "You owe",
    net: "Net",
    createGroup: "Create group",
    groupName: "Group name",
    saveGroup: "Save group",
    createExpense: "Create split expense",
    expenseDate: "Date",
    expenseDescription: "Description",
    expenseCategory: "Category",
    expensePaidBy: "Paid by",
    expenseAmount: "Amount",
    expenseSplit: "Split %",
    expenseNote: "Note",
    saveExpense: "Save expense",
    createSettlement: "Record settlement",
    settlementFrom: "Paid by",
    settlementTo: "Received by",
    settlementAmount: "Amount",
    settlementDate: "Date",
    saveSettlement: "Save settlement",
    keepSeparate: "Keep separate",
    match: "Match",
    linked: "Linked",
    imported: "Imported transaction",
    manual: "Manual split",
    editSplit: "Edit split",
    editLinkedEntry: "Edit linked entry",
    linkedEntry: "Linked entry",
    categoryBreakdown: "Category breakdown"
  },
  imports: {
    viewing: (label) => `Viewing imports for ${label}`,
    transactionCount: (count) => `${count} transactions`,
    composerTitle: "Import review",
    composerDetail: "Paste or upload a CSV, map the rows, then commit one import batch to the ledger.",
    stepsLabel: "Import steps",
    steps: ["Select file", "Data mapping", "Importing"],
    selectFileTitle: "Select file",
    selectFileDetail: "Choose one CSV and set the defaults that should apply before row-level review.",
    selectFileNextPaste: "After pasting CSV rows, review the mapping step below.",
    selectFileNextUpload: "Upload CSV is only for file uploads. Pasting works directly in the text box.",
    sourceLabel: "Source label",
    sourceLabelPlaceholder: "October UOB export",
    importNote: "Batch note",
    importNotePlaceholder: "Optional note for this import batch.",
    csvInput: "CSV content",
    csvPlaceholder: "Paste CSV rows here or upload a file below.",
    uploadFile: "Upload CSV file",
    defaultAccount: "Default account",
    ownership: "Default ownership",
    owner: "Default owner",
    split: "Shared split %",
    defaultsHint: "These top fields are batch defaults only. You can still adjust account, ownership, type, amount, category, and note per row before commit.",
    trustHint: "CSV imports are only trustworthy when date coverage is complete and overlapping statement exports are avoided.",
    mappingTitle: "Data mapping",
    mappingDetail: (count) => `Map the detected headers and review ${count} sample row${count === 1 ? "" : "s"}.`,
    nonExistingCategories: "Non-existing categories",
    categoryFallbackOther: "Categorize as Other",
    categoryFallbackBlock: "Block until mapped",
    missingRequired: (fields) => `Missing required fields: ${fields}`,
    duplicateMappings: (fields) => `Mapped twice: ${fields}`,
    mappingReady: "Mapping ready",
    sampleRows: "Sample rows",
    mappingNext: "When the mappings look right, click Preview import.",
    preview: "Preview import",
    commit: "Commit import",
    clearPreview: "Clear preview",
    unknownAccounts: "Unknown accounts need mapping before commit.",
    unknownCategories: "Unknown categories were found in the CSV.",
    categoryFallbackHelp: "Unknown categories will be normalized to Other for preview and commit.",
    categoryFallbackBlocked: "Unknown categories must be mapped or cleaned before this import can be committed.",
    previewEmpty: "No preview yet.",
    previewRows: "Preview rows",
    previewReady: "Preview ready. Review row-level details and then commit the import.",
    duplicateCandidates: (count) => `${count} possible duplicate${count === 1 ? "" : "s"} already in the ledger`,
    overlappingImports: (count) => `${count} existing import${count === 1 ? "" : "s"} overlap this date range`,
    previewCoverage: (start, end) => `Preview coverage ${start} - ${end}`,
    duplicateMatchesTitle: "Possible existing matches",
    duplicateMatchesDetail: "These rows already look similar to transactions in completed imports.",
    duplicateMatchKindExact: "Exact match",
    duplicateMatchKindNear: "Near match",
    recentTitle: "Recent imports",
    recentDetail: "Recent import batches with coverage and overlap signals.",
    importCoverage: (start, end) => `${start} - ${end}`,
    importOverlap: (count) => `${count} overlapping import${count === 1 ? "" : "s"}`,
    rollback: "Rollback import",
    rollbackDetail: (label) => `You are rolling back ${label}. Confirm?`,
    rollbackConfirm: "Confirm rollback",
    table: {
      row: "Row",
      date: "Date",
      description: "Description",
      amount: "Amount",
      type: "Type",
      account: "Account",
      category: "Category",
      owner: "Owner",
      split: "Split %",
      note: "Note"
    }
  },
  settings: {
    viewing: (label) => `Viewing settings for ${label}`,
    demoTitle: "Demo state",
    demoDetail: "The current prototype is seeded from a believable household scenario so changes can be reset quickly.",
    salaryPerPerson: "Salary per person",
    salaryHousehold: "Household salary",
    seededAt: "Last seeded",
    state: "Current mode",
    seededMode: "Seeded demo",
    emptyMode: "Empty state",
    reseed: "Reseed default demo",
    refresh: "Reload app data",
    refreshHint: "Reseed restores the default demo. Reload pulls the latest bootstrap from the local API.",
    emptyState: "Enter empty state",
    emptyStateDetail: "This clears the local demo so you can inspect blank-state behavior.",
    emptyStatePlaceholder: "Type 'empty state'",
    emptyStateConfirm: "Confirm empty state",
    peopleTitle: "People",
    peopleDetail: "Rename the household members used across views, ownership, and split labels.",
    editPerson: "Edit person",
    savePerson: "Save person",
    editPersonDetail: "Update the display name used throughout the app without changing ownership IDs.",
    personDisplayName: "Display name",
    personUsageHint: "Used in ownership, filters, and split labels.",
    accountsTitle: "Accounts",
    accountsDetail: "Reference finance accounts used by imports, entries, and planning.",
    addAccount: "+ Add account",
    editAccount: "Edit account",
    archiveAccount: "Archive account",
    archived: "Archived",
    accountName: "Display name",
    accountInstitution: "Institution",
    accountOwner: "Owner",
    accountType: "Account type",
    accountCurrency: "Currency",
    accountOpeningBalance: "Opening balance",
    accountOpeningBalanceHelp: "Use the balance immediately before your first imported transaction. Example: to start in June 2025, enter the closing balance from 31 May 2025, then import June entries.",
    reconcileAccount: "Reconcile",
    reconcileAccountTitle: "Statement checkpoint",
    reconcileAccountDetail: "Save a bank statement month-end balance for this account. The app compares your imported ledger against the latest checkpoint to flag mismatches.",
    checkpointMonth: "Statement month",
    checkpointBalance: "Statement ending balance",
    checkpointNote: "Checkpoint note",
    checkpointSave: "Save checkpoint",
    checkpointHelp: "Use the statement ending balance for the selected month. Example: Oct 2025 means the closing balance at 31 Oct 2025.",
    checkpointHistoryTitle: "Checkpoint history",
    checkpointHistoryDetail: "Recent statement checkpoints for this account, with ledger comparison.",
    trustRulesTitle: "Balance trust rules",
    trustRulesDetail: "This section explains what makes a wallet balance trustworthy and where to act when it is not.",
    trustOpeningTitle: "Before first import",
    trustOpeningDetail: "Use the balance immediately before your first imported transaction. Example: to start in June 2025, enter the closing balance from 31 May 2025, then import June entries.",
    trustOpeningAction: "Where to act: Accounts -> Edit account",
    trustCheckpointTitle: "Reconcile each statement month",
    trustCheckpointDetail: "Use the statement ending balance for the selected month. Example: Oct 2025 means the closing balance at 31 Oct 2025.",
    trustCheckpointAction: "Where to act: Accounts -> Reconcile",
    trustTransfersTitle: "Resolve transfer gaps",
    trustTransfersDetail: "These transfer rows are not fully paired yet and can leave wallet balances looking wrong until reviewed.",
    trustTransfersAction: "Where to act: Unresolved transfers below",
    unresolvedTransfersTitle: "Unresolved transfers",
    unresolvedTransfersDetail: "These transfer rows are not fully paired yet and can leave wallet balances looking wrong until reviewed.",
    openTransferReview: "Open in entries",
    reviewAllTransfers: "Review all",
    transferReviewTitle: "Transfer review",
    transferReviewDetail: "Use this list to clean up unpaired transfer rows before trusting wallet balances.",
    recentActivityTitle: "Recent balance activity",
    recentActivityDetail: "A lightweight audit trail for actions that can change balances or transfer links.",
    createAccount: "Create account",
    saveAccount: "Save account",
    createAccountDetail: "Add a tracked account for imports, entries, and planning filters.",
    editAccountDetail: "Update account metadata without changing its historical transactions.",
    archiveAccountDetail: (name) => `You are archiving ${name}. Confirm?`,
    accountBalanceHint: "Current balance = opening balance plus imported ledger activity.",
    accountHealthMatched: (month) => `Reconciled to ${month} statement`,
    accountHealthMismatch: (month, delta) => `${month} statement is off by ${delta}`,
    accountHealthNeedsCheckpoint: "No statement checkpoint yet",
    accountHealthLastImport: (date) => `Last import ${date}`,
    accountHealthNoImports: "No imports yet",
    accountHealthUnresolvedTransfers: (count) => `${count} unresolved transfer${count === 1 ? "" : "s"}`,
    categoriesTitle: "Categories",
    categoriesDetail: "Manage the default and custom categories used by imports, entries, plans, and charts.",
    addCategory: "+ Add category",
    createCategory: "Create category",
    saveCategory: "Save category",
    editCategory: "Edit category",
    deleteCategory: "Delete category",
    createCategoryDetail: "Add a category with its own slug, icon, and color.",
    editCategoryDetail: "Update category metadata without changing the entries assigned to it.",
    deleteCategoryDetail: (name) => `You are deleting ${name}. Confirm? Categories already in use cannot be deleted.`,
    categoryName: "Category name",
    categorySlug: "Slug",
    categoryIcon: "Icon",
    categoryColor: "Color"
  },
  faq: {
    viewing: (label) => `Viewing FAQ for ${label}`,
    items: [
      {
        question: "What is Monie's Map trying to answer?",
        answer:
          "Not only what got spent. The app is trying to answer what was intended, what happened, whether the difference was justified, whether savings were hurt, and which assumption was wrong."
      },
      {
        question: "What does over-granular mean here?",
        answer:
          "Over-granular means budgeting too many unstable or one-off purchases as separate planned rows. Based on the June to October sheets, your current split already looks reasonable: planned items on top and broader budget buckets below."
      },
      {
        question: "Why is the month view split into planned items and budget buckets?",
        answer:
          "Planned items are intentional commitments like savings, loan, tax, subscriptions, or specific one-offs. Budget buckets are flexible categories like food, groceries, shopping, and transport."
      },
      {
        question: "Should this FAQ be updated later?",
        answer:
          "Yes. The FAQ is a living product document and should be updated whenever setup, workflow, philosophy, or user-facing behavior changes."
      }
    ]
  }
};
