export const messages = {
  common: {
    loading: "Loading...",
    loadingLatest: "Loading latest data...",
    refresh: "Refresh",
    saving: "Saving...",
    working: "Working...",
    bootstrapErrorTitle: "Dashboard data could not load.",
    emptyValue: "—",
    viewingDot: (label) => `Viewing • ${label}`,
    contextWithView: (left, right) => `${left} • ${right}`,
    triplet: (first, second, third) => `${first} • ${second} • ${third}`,
    moneyAndPercent: (moneyValue, percentage) => `${moneyValue} • ${percentage}%`
  },
  views: {
    household: "Household"
  },
  tabs: {
    summary: "Summary",
    month: "Month",
    entries: "Entries",
    splits: "Splits",
    imports: "Imports",
    settings: "Settings",
    faq: "FAQ",
    ariaLabel: "Dashboard sections"
  },
  period: {
    month: "Month",
    year: "Range",
    currentYear: "2025",
    previousAriaLabel: "Previous period",
    nextAriaLabel: "Next period"
  },
  summary: {
    spendingMix: "Spending Mix",
    rangeOverall: "Range overall",
    fromMonth: "From",
    toMonth: "To",
    focusMonth: "Focus",
    intentVsOutcome: "Intent vs Outcome",
    intentVsOutcomeDetail: "Monthly comparison with expandable detail.",
    incomeLabel: (plannedValue, actualValue) => `Planned income ${plannedValue} • Actual income ${actualValue}`,
    totalSpend: "Total spend",
    table: {
      metric: "Metric",
      estimate: "Planned",
      actual: "Actual",
      variance: "Variance",
      note: "Context",
      income: "Income",
      expectedExpenses: "Expected spend",
      expectedSavings: "Savings goal",
      actualSavings: "Realized savings"
    }
  },
  month: {
    incomeSectionTitle: "Income",
    incomeSectionDetail: "Planned income sources that fund the month before expenses are allocated.",
    actions: "Actions",
    duplicateMonth: "Duplicate month",
    resetMonth: "Reset month",
    resetMonthDetail: "This clears the current month's plan rows, entries, and summary totals.",
    resetMonthPlaceholder: "Type 'reset month'",
    resetMonthConfirm: "Confirm reset month",
    deleteMonth: "Delete month",
    deleteMonthDetail: "This removes the current month entirely from the demo, including its summary snapshot.",
    deleteMonthPlaceholder: "Type 'delete month'",
    deleteMonthConfirm: "Confirm delete month",
    addIncomeSource: "+ Add income source",
    editIncomeSource: "Edit income source",
    incomeRowNote: "Main planned income source for the month.",
    extraIncomeNote: "Additional planned income source.",
    addPlannedItem: "+ Add planned item",
    editPlannedItem: "Edit planned item",
    addBudgetBucket: "+ Add budget bucket",
    editBudgetBucket: "Edit budget bucket",
    newPlannedItemNote: "New planned item.",
    newBudgetBucketNote: "New budget bucket.",
    doneEdit: "Done",
    cancelEdit: "Cancel",
    notesTitle: "Monthly Note",
    notesDetail: "Why the month looked like this.",
    accountsTitle: "Accounts",
    accountsDetail: "Tracked finance accounts.",
    editHint: "Click a row to edit the plan. Actual stays read-only because it should come from entries.",
    readOnlyCombinedHint: "Combined household view is read-only. Switch to a person view to edit the plan.",
    table: {
      category: "Category",
      day: "Date",
      item: "Item",
      planned: "Planned",
      actual: "Actual",
      variance: "Variance",
      total: "Total",
      account: "Account",
      note: "Note"
    }
  },
  entries: {
    viewing: (label) => `Viewing entries for ${label}`,
    wallet: "By wallet",
    category: "By category",
    person: "By people",
    resetFilters: "Reset filters",
    allWallets: "All wallets",
    allCategories: "All categories",
    allPeople: "All people",
    type: "By type",
    allTypes: "All types",
    totalsLabel: "Entry totals",
    totalSpend: "Spend",
    totalOutflow: "Outflow",
    totalIncome: "Income",
    totalDifference: "Difference",
    dateNet: "Daily net",
    addEntry: "+ Add entry",
    editCategory: "Category",
    editDate: "Date",
    editType: "Type",
    editAmount: "Amount",
    editDescription: "Description",
    editWallet: "Wallet",
    editOwner: "Owner",
    editSplit: "Split %",
    editNote: "Note",
    editTransferDirection: "Transfer direction",
    scope: "Scope",
    shared: "Shared",
    offsetsCategory: " • offsets category",
    split: "Split",
    counterpart: "Counterpart",
    doneEdit: "Done",
    cancelEdit: "Cancel",
    addToSplits: "Add to splits",
    noSpendBreakdown: "No spend rows in this view.",
    noEntries: "No entries match this view.",
    walletViewMismatchTitle: "This wallet is outside the current view.",
    walletViewMismatchDetail: (walletLabel, ownerLabel, viewLabel) => `No entries match ${viewLabel}'s view. ${walletLabel} belongs to ${ownerLabel}, and there are no shared rows for this wallet this month.`,
    walletViewMismatchHouseholdAction: "View household",
    walletViewMismatchOwnerAction: (ownerLabel) => `View ${ownerLabel}`
  },
  splits: {
    viewing: (label) => `Viewing splits for ${label}`,
    nonGroup: "Non-group expenses",
    addGroup: "+",
    matches: "Matches",
    reviewMatches: "Review matches",
    backToGroup: "Back to split group",
    entries: "entries",
    allClear: "All clear",
    toReview: (count) => `${count} to review`,
    expenseMatches: "Expense matches",
    settlementMatches: "Settlement matches",
    addExpense: "+ Add expense",
    settleUp: "Settle up",
    settledUp: "Settled up",
    noGroups: "No split groups yet.",
    noEntries: "No split entries yet for this group.",
    noMatches: "No split matches to review right now.",
    youAreOwed: "You are owed",
    youOwe: "You owe",
    net: "Net",
    createGroup: "Create group",
    groupName: "Group name",
    saveGroup: "Save group",
    createExpense: "Create split expense",
    expenseDate: "Date",
    expenseDescription: "Description",
    expenseCategory: "Category",
    expensePaidBy: "Paid by",
    expenseAmount: "Amount",
    expenseSplit: "Split %",
    expenseExactAmount: (personName) => `${personName} amount`,
    expenseNote: "Note",
    saveExpense: "Save expense",
    createSettlement: "Record settlement",
    settlementFrom: "Paid by",
    settlementTo: "Received by",
    settlementAmount: "Amount",
    settlementDate: "Date",
    saveSettlement: "Save settlement",
    keepSeparate: "Keep separate",
    match: "Match",
    linked: "Linked",
    imported: "Imported transaction",
    manual: "Manual split",
    editSplit: "Edit split",
    viewLinkedEntry: "View entry",
    linkedEntry: "Linked entry",
    categoryBreakdown: "Category breakdown"
  },
  imports: {
    viewing: (label) => `Viewing imports for ${label}`,
    transactionCount: (count) => `${count} transactions`,
    composerTitle: "Import and certify",
    composerDetail: "Paste or upload a CSV, upload a supported PDF statement, or upload a supported current-transaction XLS. PDF statements certify the period like a bank sync; mid-cycle files keep the working ledger current.",
    stepsLabel: "Import steps",
    steps: ["Select file", "Data mapping", "Review"],
    selectFileTitle: "Select file",
    selectFileDetail: "Choose one CSV, supported PDF statement, or supported current-transaction XLS and set the defaults that should apply before row-level review.",
    selectFileNextPaste: "After pasting CSV rows, review the mapping step below.",
    selectFileNextUpload: "PDF statements and supported current-transaction XLS files are converted into reviewable rows. Pasting CSV works directly in the text box.",
    sourceLabel: "Source label",
    sourceLabelPlaceholder: "October UOB export",
    importNote: "Batch note",
    importNotePlaceholder: "Optional note for this import batch.",
    csvInput: "CSV content",
    csvPlaceholder: "Paste CSV rows here, or upload a CSV/PDF/XLS below.",
    uploadFile: "Upload CSV, PDF, or XLS",
    dropzoneTitle: "Drop a CSV, PDF, or XLS here",
    dropzoneDetail: "Click to browse, or drag a supported statement or current-transaction export onto this area.",
    uploadStatusWorking: "Working",
    uploadStatusReady: "Ready",
    uploadStatusError: "Import needs attention",
    uploadReading: (fileName) => `Reading ${fileName}.`,
    uploadExtracting: (fileName) => `Extracting text from ${fileName}.`,
    uploadParsing: (fileName) => `Parsing import rows from ${fileName}.`,
    uploadPreviewing: (count) => `Preparing preview for ${count} detected row${count === 1 ? "" : "s"}.`,
    uploadReady: (count) => `${count} row${count === 1 ? "" : "s"} ready for review.`,
    uploadStatementReady: (rowCount, accountCount) => `${rowCount} row${rowCount === 1 ? "" : "s"} ready for review across ${accountCount} statement account${accountCount === 1 ? "" : "s"}.`,
    uploadCsvReady: (fileName) => `${fileName} is loaded. Review the mapping below.`,
    defaultAccount: "Default account",
    ownership: "Default ownership",
    owner: "Default owner",
    split: "Shared split %",
    defaultsHint: "These top fields are fallbacks. Direct rows use the mapped account owner when one exists, and you can still adjust account, ownership, type, amount, category, and note per row before commit.",
    trustHint: "Statement imports are only trustworthy when date coverage is complete and overlapping exports are reviewed.",
    mappingTitle: "Data mapping",
    mappingDetail: (count) => `Map the detected headers and review ${count} sample row${count === 1 ? "" : "s"}.`,
    nonExistingCategories: "Non-existing categories",
    categoryFallbackOther: "Categorize as Other",
    categoryFallbackBlock: "Block until mapped",
    missingRequired: (fields) => `Missing required fields: ${fields}`,
    duplicateMappings: (fields) => `Mapped twice: ${fields}`,
    mappingReady: "Mapping ready",
    sampleRows: "Sample rows",
    mappingNext: "When the mappings look right, click Preview import.",
    preview: "Preview import",
    commit: "Commit import to ledger",
    saveStatementCheckpoints: "Refresh statement checkpoints",
    refreshCoveredStatementCheckpoint: "Refresh covered statement checkpoint",
    saveEmptyStatementCheckpoint: "Save empty statement checkpoint",
    commitFailed: "Import commit failed. No partial transactions were kept.",
    clearPreview: "Clear preview",
    startOver: "Start over",
    unknownAccounts: "Unknown accounts need mapping before commit.",
    accountMappingTitle: "Statement account mapping",
    accountMappingDetail: "Match each detected statement account to the account that should receive these rows and checkpoints.",
    detectedAccount: (accountName) => `Detected: ${accountName}`,
    chooseAccount: "Choose account",
    createDetectedAccount: "Create account",
    accountMappingRefreshing: "Refreshing preview after account mapping.",
    accountMappingRefreshed: "Preview refreshed with the selected account mapping.",
    accountCreatedFromStatement: (accountName) => `Created ${accountName} and mapped the statement rows.`,
    unknownCategories: "Unknown categories were found in the CSV.",
    categoryFallbackHelp: "Unknown categories will be normalized to Other for preview and commit.",
    categoryFallbackBlocked: "Unknown categories must be mapped or cleaned before this import can be committed.",
    previewEmpty: "No preview yet.",
    previewRows: "Preview rows",
    previewReady: "Preview ready. Matching rows can be reconciled in place before commit instead of creating duplicate ledger entries.",
    largeImportNotice: (count) => `Large import: ${count} rows will be committed in protected chunks. If Cloudflare still rejects the request, split the CSV into smaller batches.`,
    reconciliationCandidates: (count) => `${count} entry reconciliation match${count === 1 ? "" : "es"} need a decision`,
    reconciledExistingRows: (count, sourceType) => sourceType === "pdf"
      ? `${count} provisional row${count === 1 ? "" : "s"} will be certified by the statement`
      : `${count} manual row${count === 1 ? "" : "s"} will be promoted in place by this import`,
    overlappingImports: (count) => `${count} prior import${count === 1 ? "" : "s"} in this account period`,
    exceptionRegisterTitle: "Exceptions to resolve",
    exceptionRegisterDetail: "The app will handle matched statement rows automatically. These are the remaining controls that need attention before the period can close.",
    exceptionKinds: {
      unknown_account: (count) => `${count} account mapping issue${count === 1 ? "" : "s"}`,
      unknown_category: (count) => `${count} category issue${count === 1 ? "" : "s"}`,
      review_rows: (count) => `${count} row decision${count === 1 ? "" : "s"}`,
      statement_mismatch: (count) => `${count} statement mismatch${count === 1 ? "" : "es"}`,
      account_identity: (count) => `${count} account identity proof${count === 1 ? "" : "s"}`,
      entry_reconciliation: (count) => `${count} entry reconciliation exception${count === 1 ? "" : "s"}`,
      prior_import_context: (count) => `${count} prior import context item${count === 1 ? "" : "s"}`
    },
    previewGuardrailsLabel: "Import preview checks",
    previewCommitSummaryLabel: "Import commit summary",
    previewCoverage: (start, end) => `Preview coverage ${start} - ${end}`,
    previewOverlapTitle: "Prior import context",
    previewOverlapScopeAriaLabel: "How overlap checks work",
    previewOverlapScopeTitle: "Scope",
    previewOverlapScopeDetail: "The overlap check is account-aware and import-aware.",
    previewOverlapScopeItems: [
      "It checks against all completed historical imports.",
      "It only checks accounts present in the current preview, after account mapping.",
      "If a PDF contains multiple account sections, it can detect overlaps for any of those mapped accounts.",
      "It does not compare against unrelated accounts.",
      "It ignores draft and rolled-back imports."
    ],
    previewOverlapDetail: "Earlier imports in the same account period can be normal when mid-cycle activity already exists. Statement-certified rows are handled automatically; use this section only for unresolved exceptions.",
    previewOverlapActionTitle: "What to do",
    previewOverlapActions: ({ skippedPreviewRowCount, needsReviewPreviewRowCount, hasStatementReconciliationMismatch, hasStatementReconciliations }) => {
      const actions = [
        "Use the entries below as context for earlier committed ledger rows inside this statement's date range."
      ];
      if (needsReviewPreviewRowCount) {
        actions.push("Resolve rows still marked Needs review before committing.");
      } else if (skippedPreviewRowCount) {
        actions.push("Rows listed as already covered can stay out of the import unless the statement check shows the ledger is missing them.");
      } else {
        actions.push("If there are no unresolved rows, this is context rather than a blocker.");
      }
      if (hasStatementReconciliations) {
        actions.push(hasStatementReconciliationMismatch
          ? "Do not commit yet if the statement certification check is still mismatched. Fix account mapping, missing rows, or row direction first."
          : "When the statement certification check is matched, mark the context Reviewed and commit.");
      } else {
        actions.push("Mark the context Reviewed after the preview rows match what should be added to the ledger.");
      }
      return actions;
    },
    previewOverlapMismatchExplained: (amount) => `The statement difference is exactly ${amount}, which matches the overlapping entries below. That usually means a prior import is on this account but is not part of this statement. Check whether that earlier import belongs to another card account, then roll it back or remap before committing this statement.`,
    previewOverlapEntriesLabel: "Already committed overlapping entries",
    dismissOverlap: "Reviewed",
    statementReconciliationTitle: "Statement certification check",
    statementReconciliationMatchedDetail: "The preview reconciles to the official statement balance. Matching provisional rows will be certified without changing user annotations.",
    statementReconciliationMismatchDetail: "The statement cannot close yet. Check account mapping, missing or extra rows, row direction, or account identity before committing.",
    statementReconciliationRefresh: "Refresh check",
    statementReconciliationRefreshing: "Refreshing statement certification check.",
    statementReconciliationRefreshed: "Statement certification check refreshed.",
    statementReconciliationAccount: (accountName, month) => `${accountName} • ${month}`,
    statementReconciliationDelta: (amount) => `Difference ${amount}`,
    statementReconciliationStatus: {
      matched: "Matched",
      mismatch: "Mismatch",
      unknown_account: "Needs account",
      identity_unconfirmed: "Needs account proof"
    },
    reconciliationMatchesTitle: "Entry reconciliation matches needing decision",
    reconciliationMatchesDetail: "These rows could not be reconciled automatically. Review only these exceptions before commit.",
    certifiedConflictTitle: (count) => count === 1 ? "Certified row conflict" : `Certified row conflicts (${count})`,
    certifiedConflictDetail: "These rows are already certified somewhere in the ledger, but they do not safely reconcile this statement checkpoint. They are blocking accounting conflicts, not rows to include again.",
    certifiedConflictRow: (date, description, amount) => `${date} • ${description} • ${amount}`,
    duplicateMatchKindExact: "Exact match",
    duplicateMatchKindProbable: "Probable match",
    duplicateMatchKindNear: "Near match",
    duplicateRowDetail: (match) => `Already in ledger: ${match}`,
    viewLedgerMatch: "View match",
    duplicateMatchPopoverTitle: "Ledger match",
    duplicateMatchPopoverDetail: "Compare the incoming row with the existing ledger row before deciding.",
    duplicateMatchIncomingLabel: "Incoming row",
    duplicateMatchLedgerLabel: "Ledger row",
    bankCertificationStatusLine: (label) => `Bank certification status: ${label}`,
    bankCertificationStatusIncomingStatement: "Statement certified on commit",
    openLedgerEntry: "Open ledger entry",
    needsReview: "Needs review",
    willImportRows: (count) => `${count} row${count === 1 ? "" : "s"} will import`,
    willReconcileExistingRows: (count, sourceType) => sourceType === "pdf"
      ? `${count} existing row${count === 1 ? "" : "s"} will be certified by the statement`
      : `${count} existing row${count === 1 ? "" : "s"} will be promoted in place`,
    willSaveStatementCheckpoints: (count) => `${count} statement checkpoint${count === 1 ? "" : "s"} will refresh`,
    willSkipRows: (count) => `${count} row${count === 1 ? "" : "s"} already covered`,
    needsReviewRows: (count) => `${count} row${count === 1 ? "" : "s"} need review`,
    noRowsToImport: "No new ledger rows will be created. You can still refresh statement checkpoints and certification when the checks match.",
    noRowsToImportCoveredStatement: "This statement's rows are already in the ledger. No duplicate ledger rows will be created. You can still refresh the statement checkpoint and certification.",
    noRowsToImportEmptyStatement: "This statement has no transaction rows. Only the statement checkpoint will be saved.",
    skipPreviewRow: "Exclude row",
    restorePreviewRow: "Include row",
    restoreExactCoveredRowConfirm: "This row is marked as an exact already-covered match. Including it again can create a duplicate ledger entry. Continue?",
    importPreviewRow: "Include row",
    promoteExistingPreviewRow: "Promote existing row",
    importAsNewPreviewRow: "Import as new row",
    skippedRowsTitle: (count) => `Already covered rows (${count})`,
    statementCheckpointsTitle: (count) => count === 1 ? "Statement checkpoint" : "Statement checkpoints",
    statementCheckpointsDetail: (count) => count === 1
      ? "This statement balance will be saved during commit. Adjust it here before importing."
      : `This PDF contains ${count} account sections, so each account needs its own checkpoint. For card statements, start date is the first included post date found in that account section. Adjust them here before importing.`,
    duplicateCheckpointAccounts: (accounts) => `Each checkpoint needs a different account. Check: ${accounts}`,
    statementCheckpointAccount: "Account",
    statementCheckpointMonth: "Statement month",
    statementCheckpointStart: "Start date",
    statementCheckpointEnd: "End date",
    statementCheckpointBalance: "Ending balance",
    statementCheckpointNote: "Note",
    recentTitle: "Recent imports",
    recentDetail: "Recent import batches with coverage and overlap signals.",
    recentAccountFilter: "By account",
    recentAllAccounts: "All accounts",
    recentEmpty: "No imports match this account filter.",
    recentRefreshing: "Updating recent imports...",
    recentStatementCertificates: (count) => `${count} statement certificate${count === 1 ? "" : "s"}`,
    recentStatementCertificateException: "certificate exception",
    recentPageSummary: (start, end, total) => `Showing ${start}-${end} of ${total} imports`,
    recentPageCount: (page, pageCount) => `Page ${page} of ${pageCount}`,
    previousPage: "Previous",
    nextPage: "Next",
    importCoverage: (start, end) => `${start} - ${end}`,
    importKindPdfStatement: "PDF statement",
    importKindMidcycle: "Mid-cycle",
    importKindManual: "Manual",
    importKindCsv: "CSV import",
    importOverlap: (count) => `${count} overlapping import${count === 1 ? "" : "s"}`,
    overlapPopoverTitle: "Overlapping imports",
    overlapPopoverDetail: "Completed imports for the same account with a date range that crosses this batch.",
    overlapPopoverEmpty: "No same-account overlaps are attached to this import.",
    rollback: "Rollback import",
    rollbackDetail: (label) => `You are rolling back ${label}. Confirm?`,
    rollbackConfirm: "Confirm rollback",
    statementRollbackLocked: "Statement locked",
    statementRollbackLockedDetail: "PDF statement imports are locked after they certify existing rows or when a later statement exists for the same account.",
    table: {
      row: "Row",
      date: "Date",
      description: "Description",
      amount: "Amount",
      type: "Type",
      account: "Account",
      category: "Category",
      owner: "Owner",
      split: "Split %",
      note: "Note",
      actions: "Actions"
    }
  },
  settings: {
    viewing: (label) => `Viewing settings for ${label}`,
    demoTitle: "Demo state",
    demoDetail: "The current prototype is seeded from a believable household scenario so changes can be reset quickly.",
    salaryHousehold: "Household salary",
    seededAt: "Last seeded",
    state: "Current mode",
    seededMode: "Seeded demo",
    emptyMode: "Empty state",
    reseed: "Reseed default demo",
    refresh: "Reload app data",
    refreshHint: "Reseed restores the default demo. Empty state clears finance data. Reload only refreshes the visible app data from the current database.",
    reloadDataTitle: "Reload app data",
    reloadDataDetail: "This reloads the latest accounts, entries, imports, checkpoints, plans, splits, categories, and settings from the current database. It does not reseed, delete, or import anything.",
    reloadDataPlaceholder: "Type 'reload data'",
    reloadDataConfirm: "Confirm reload",
    emptyState: "Enter empty state",
    emptyStateDetail: "This clears accounts, entries, imports, checkpoints, month plans, snapshots, and splits. Only the household, people, categories, and category rules remain.",
    emptyStatePlaceholder: "Type 'empty state'",
    emptyStateConfirm: "Confirm empty state",
    emptyStateStillHasAccounts: "Empty-state reset finished, but accounts are still present after reload. Refresh the page and check that the reset ran against the same database as this app.",
    peopleTitle: "People",
    peopleDetail: "Rename the household members used across views, ownership, and split labels.",
    editPerson: "Edit person",
    savePerson: "Save person",
    editPersonDetail: "Update the display name used throughout the app without changing ownership IDs.",
    personDisplayName: "Display name",
    personUsageHint: "Used in ownership, filters, and split labels.",
    accountsTitle: "Accounts",
    accountsDetail: "Reference finance accounts used by imports, entries, and planning.",
    addAccount: "+ Add account",
    editAccount: "Edit account",
    archiveAccount: "Archive account",
    archived: "Archived",
    accountName: "Display name",
    accountInstitution: "Institution",
    accountOwner: "Owner",
    accountType: "Account type",
    accountCurrency: "Currency",
    accountOpeningBalance: "Opening balance",
    accountOpeningBalanceHelp: "Use the balance immediately before your first imported transaction. Example: to start in June 2025, enter the closing balance from 31 May 2025, then import June entries.",
    reconcileAccount: "Reconcile",
    reconcileAccountTitle: "Statement checkpoint",
    reconcileAccountDetail: "Save a statement closing balance for this account. The app compares your imported ledger against the latest checkpoint to flag mismatches.",
    checkpointMonth: "Statement month",
    checkpointStartDate: "Statement start date",
    checkpointEndDate: "Statement end date",
    checkpointBalance: "Statement ending balance",
    checkpointNote: "Checkpoint note",
    checkpointSave: "Save checkpoint",
    checkpointHelp: "Optional. Leave blank for a normal calendar-month statement; fill these for credit-card cycles that include prior-month rows.",
    checkpointHistoryTitle: "Checkpoint history",
    checkpointHistoryDetail: "Recent statement checkpoints for this account, with ledger comparison.",
    checkpointEdit: "Edit checkpoint",
    checkpointDelete: "Delete checkpoint",
    checkpointDeleteDetail: (month) => `You are deleting the ${month} statement checkpoint. Confirm?`,
    checkpointExport: "Download CSV",
    statementCompareOpen: "Compare statement",
    statementCompareUpload: "Compare statement",
    statementCompareTitle: "Statement comparison",
    statementComparePanelTitle: (accountName, month) => `${accountName} ${month} statement comparison`,
    statementComparePanelDetail: "Upload the bank statement here to compare it against the committed ledger for this checkpoint period. This does not import new rows. The statement period is filled from the PDF after upload.",
    statementCompareDelta: (amount) => `Mismatched amount ${amount}`,
    statementCompareCheckpointPeriod: (start, end) => `Checkpoint period ${start} - ${end}`,
    statementCompareUploadedPeriod: (start, end) => `Uploaded statement period ${start} - ${end}`,
    statementCompareAddEntry: "Add to ledger",
    statementCompareAddEntryTitle: "Add ledger entry",
    statementCompareAddEntrySave: "Add entry",
    statementCompareEntryAdded: "Ledger entry added. Re-run the statement comparison to fully verify the checkpoint.",
    statementCompareReading: (fileName) => `Reading ${fileName}.`,
    statementCompareChecking: (count) => `Comparing ${count} statement row${count === 1 ? "" : "s"} against the current ledger.`,
    statementCompareReady: (result) => `${result.matchedRowCount} matched, ${result.unmatchedStatementRows.length} missing from ledger, ${result.unmatchedLedgerRows.length} extra in ledger.`,
    statementCompareSummary: (result) => `${result.accountName} ${result.checkpointMonth}: ${result.matchedRowCount} of ${result.statementRowCount} statement rows matched`,
    statementComparePossibleTitle: "Possible near matches",
    statementCompareDirectionTitle: "Direction mismatches",
    statementCompareDirectionDetail: "These look like the same transaction, but one side is income and the other side is expense. That changes the balance by twice the amount.",
    statementCompareFixDirection: "Fix ledger direction",
    statementCompareFixDirectionTitle: "Fix ledger direction",
    statementCompareFixDirectionSave: "Update ledger row",
    statementCompareDirectionFixed: "Ledger row direction updated. The comparison result was updated in place.",
    statementCompareDuplicateTitle: "Duplicate check",
    statementCompareDuplicateNone: "No duplicate-looking statement or ledger rows found.",
    statementCompareDuplicateSummary: (statementCount, ledgerCount) => `${statementCount} duplicate-looking statement group${statementCount === 1 ? "" : "s"}, ${ledgerCount} duplicate-looking ledger group${ledgerCount === 1 ? "" : "s"}.`,
    statementCompareDuplicateStatement: "Statement duplicates",
    statementCompareDuplicateLedger: "Ledger duplicates",
    statementCompareMissingTitle: "In statement, not ledger",
    statementCompareExtraTitle: "In ledger, not statement",
    statementCompareNone: "None found.",
    statementComparePossibleRow: (candidate) => candidate.amountDirectionMismatch
      ? `${candidate.statementRow.date} ${candidate.statementRow.description} has the same amount as ${candidate.ledgerRow.date} ${candidate.ledgerRow.description}, but the direction is different.`
      : `${candidate.statementRow.date} ${candidate.statementRow.description} may match ${candidate.ledgerRow.date} ${candidate.ledgerRow.description}`,
    trustRulesTitle: "Balance trust rules",
    trustRulesDetail: "This section explains what makes a wallet balance trustworthy and where to act when it is not.",
    trustRulesDetailWithExceptions: (count) => `${count} open reconciliation exception${count === 1 ? "" : "s"} should be resolved before treating balances as certified.`,
    trustOpeningTitle: "Before first import",
    trustOpeningDetail: "Use the balance immediately before your first imported transaction. Example: to start in June 2025, enter the closing balance from 31 May 2025, then import June entries.",
    trustOpeningAction: "Where to act: Accounts -> Edit account",
    trustCheckpointTitle: "Reconcile each statement month",
    trustCheckpointDetail: "Use the statement ending balance for the selected month. Example: Oct 2025 means the closing balance at 31 Oct 2025.",
    trustCheckpointAction: "Where to act: Accounts -> Reconcile",
    trustTransfersTitle: "Resolve transfer gaps",
    trustTransfersDetail: "These transfer rows are not fully paired yet and can leave wallet balances looking wrong until reviewed.",
    trustTransfersAction: "Where to act: Unresolved transfers below",
    reconciliationExceptionsTitle: "Reconciliation exceptions",
    reconciliationExceptionsDetail: "Track known gaps such as missing bank rows, duplicate-looking imports, timing differences, or ledger rows that still need proof.",
    addReconciliationException: "Add exception",
    saveReconciliationException: "Save exception",
    resolveReconciliationException: "Resolve",
    cancelException: "Cancel",
    noReconciliationExceptions: "No reconciliation exceptions recorded.",
    exceptionAccountLabel: "Account",
    exceptionNoAccount: "No account",
    exceptionMonthLabel: "Statement month",
    exceptionKindLabel: "Issue type",
    exceptionSeverityLabel: "Severity",
    exceptionTitleLabel: "Title",
    exceptionTitlePlaceholder: "Example: Apple Pay bus fare not in bank export yet",
    exceptionNoteLabel: "Note",
    exceptionNotePlaceholder: "What you checked, what is still pending, and what will close this.",
    exceptionOpen: "Open",
    exceptionResolved: "Resolved",
    exceptionKindLabels: {
      missing_bank_row: "Missing bank row",
      extra_ledger_row: "Extra ledger row",
      duplicate: "Duplicate",
      direction_mismatch: "Direction mismatch",
      wrong_account: "Wrong account",
      timing_difference: "Timing difference",
      manual_review: "Manual review",
      adjustment_needed: "Adjustment needed"
    },
    exceptionSeverityLabels: {
      info: "Info",
      review: "Review",
      blocking: "Blocking"
    },
    unresolvedTransfersTitle: "Unresolved transfers",
    unresolvedTransfersDetail: "These transfer rows are not fully paired yet and can leave wallet balances looking wrong until reviewed.",
    unresolvedTransfersDetailWithCount: (count) => `${count} transfer rows are not fully paired yet and can leave wallet balances looking wrong until reviewed.`,
    openTransferReview: "Open in entries",
    clearTransfer: "Clear",
    clearAllTransfers: "Clear all",
    transferPage: (page, pageCount, count) => `Page ${page} of ${pageCount} (${count} transfers)`,
    reviewAllTransfers: "Review all",
    transferReviewTitle: "Transfer review",
    transferReviewDetail: "Use this list to clean up unpaired transfer rows before trusting wallet balances.",
    recentActivityTitle: "Recent balance activity",
    recentActivityDetail: "A lightweight audit trail for actions that can change balances or transfer links.",
    createAccount: "Create account",
    saveAccount: "Save account",
    createAccountDetail: "Add a tracked account for imports, entries, and planning filters.",
    editAccountDetail: "Update account metadata without changing its historical transactions.",
    archiveAccountDetail: (name) => `You are archiving ${name}. Confirm?`,
    accountBalanceHint: "Current balance = opening balance plus imported ledger activity.",
    accountHealthMatched: (month) => `Reconciled to ${month} statement`,
    accountHealthMismatch: (month, delta) => `${month} statement is off by ${delta}`,
    accountHealthNeedsCheckpoint: "No statement checkpoint yet",
    accountHealthLastImport: (date) => `Last import ${date}`,
    accountHealthNoImports: "No imports yet",
    accountHealthUnresolvedTransfers: (count) => `${count} unresolved transfer${count === 1 ? "" : "s"}`,
    categoriesTitle: "Categories",
    categoriesDetail: "Manage the default and custom categories used by imports, entries, plans, and charts.",
    addCategory: "+ Add category",
    createCategory: "Create category",
    saveCategory: "Save category",
    editCategory: "Edit category",
    deleteCategory: "Delete category",
    createCategoryDetail: "Add a category with its own slug, icon, and color.",
    editCategoryDetail: "Update category metadata without changing the entries assigned to it.",
    deleteCategoryDetail: (name) => `You are deleting ${name}. Confirm? Categories already in use cannot be deleted.`,
    categoryName: "Category name",
    categorySlug: "Slug",
    categoryIcon: "Icon",
    categoryColor: "Color",
    categoryRulesTitle: "Category matching",
    categoryRulesDetail: "Rules categorize new import rows during preview and can correct the bank parser when it guesses wrong. Capitalization, spaces, and punctuation do not matter. Write one merchant word or phrase, or separate a few words with commas when all of them must appear, like paynow-fast, lunch. Very short names must appear as their own word, and lower priority numbers are checked first.",
    categoryRuleSuggestionsTitle: "Suggestions",
    categoryRuleSuggestionsDetail: "Repeated manual category changes are held here for review. Add the rule, edit it first, or ignore it.",
    categoryRuleSuggestionsCount: (count) => `${count} pending`,
    categoryRuleSuggestionSeen: (count) => `Seen ${count} time${count === 1 ? "" : "s"}`,
    categoryRuleSuggestionNote: (count) => `Accepted from ${count} manual category correction${count === 1 ? "" : "s"}.`,
    acceptCategoryRuleSuggestion: "Add rule",
    editCategoryRuleSuggestion: "Edit first",
    ignoreCategoryRuleSuggestion: "Ignore",
    settingsCategorySuggestionBadgeTitle: (count) => `${count} pending category match suggestion${count === 1 ? "" : "s"}`,
    addCategoryRule: "+ Add match rule",
    collapseCategoryRules: "Collapse all",
    expandCategoryRules: "Expand all",
    createCategoryRule: "Create match rule",
    editCategoryRule: "Edit match rule",
    saveCategoryRule: "Save rule",
    deleteCategoryRule: "Delete rule",
    deleteCategoryRuleDetail: (pattern) => `You are deleting the ${pattern} category match rule. Confirm?`,
    categoryRuleGroupCount: (count) => `${count} ${count === 1 ? "rule" : "rules"}`,
    categoryRuleDialogDetail: "Match merchant text from bank rows to a category before review. If a rule matches, it wins over the parser's first guess.",
    categoryRulePattern: "Merchant text",
    categoryRuleCategory: "Category",
    categoryRulePriority: "Priority",
    categoryRulePriorityHelp: "Lower numbers run first. Use this when one merchant text is more specific than another.",
    categoryRuleStatus: "Status",
    categoryRuleActive: "Active",
    categoryRuleInactive: "Inactive",
    categoryRuleNote: "Note",
    categoryRulePriorityValue: (priority) => `Priority ${priority}`
  },
  faq: {
    viewing: (label) => `Viewing FAQ for ${label}`,
    items: [
      {
        question: "What is Monie's Map trying to answer?",
        answer:
          "Not only what got spent. The app is trying to answer what was intended, what happened, whether the difference was justified, whether savings were hurt, and which assumption was wrong."
      },
      {
        question: "What does over-granular mean here?",
        answer:
          "Over-granular means budgeting too many unstable or one-off purchases as separate planned rows. Based on the June to October sheets, your current split already looks reasonable: planned items on top and broader budget buckets below."
      },
      {
        question: "Why is the month view split into planned items and budget buckets?",
        answer:
          "Planned items are intentional commitments like savings, loan, tax, subscriptions, or specific one-offs. Budget buckets are flexible categories like food, groceries, shopping, and transport."
      },
      {
        question: "Should this FAQ be updated later?",
        answer:
          "Yes. The FAQ is a living product document and should be updated whenever setup, workflow, philosophy, or user-facing behavior changes."
      }
    ]
  }
};
